### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by RILUCK** [TufayelLUS/LinkedIn-Lead-Scraper#1]
Traceback (most recent call last):
  File "CompanyWise_Leads.py", line 170, in <module>
    profile_list.extend(connection.listProfiles(company_id, page_no))
  File "CompanyWise_Leads.py", line 114, in listProfiles
    profiles = resp.get('data').get('elements')[0].get('elements')
IndexError: list index out of range

**Comment by RILUCK** [comment]
@TufayelLUS how can we solve this issue or limit the number of loops for less than 10000 profiles?

**Comment by TufayelLUS** [comment]
Hi @RILUCK
Sorry, I was away for a long due to some issues. I noticed your issue now. Not sure about the error appearing. A possible chance that there have been any changes in the LinkedIn API or there was no profile returned during the request.
The result should be automatically adjusted if the loops are less than 10K profiles as designed in the code. But I am unsure why this is happening. I suspect about the change in LinkedIn api response.

**Comment by RILUCK** [comment]
> Hi @RILUCK
> Sorry, I was away for a long due to some issues. I noticed your issue now. Not sure about the error appearing. A possible chance that there have been any changes in the LinkedIn API or there was no profile returned during the request.
> The result should be automatically adjusted if the loops are less than 10K profiles as designed in the code. But I am unsure why this is happening. I suspect about the change in LinkedIn api response.

@TufayelLUS I see that it is getting null response in contact information email. Can you please re-run and check why it is giving null information for all contacts and not generating emails.csv file. I agree that now days there is hide email option is there in Linkedin but for all profiles it is not getting any emails.

**Comment by TufayelLUS** [comment]
I am currently facing a wifi outage here, so Linkedin is not accepting my IP to login via the script at this moment. When I get my wifi back, I will have a look again at this if I get time to sit with it.

**Comment by adelinglibert** [comment]
Hi @TufayelLUS , have you figured out the issue ?

**Comment by Jayasoruban** [comment]
Hello Sir, I'm unable find the API link that you have given in the code, I could find a similar API link after logging into LINKEDIN inside the Networks tab from inspect elements. But when I use that link in python its throwing me a error.

Please let me know where to find these two API Links it would be of great help to me.
api_link = 'https://www.linkedin.com/voyager/api/organization/companies?decorationId=com.linkedin.voyager.deco.organization.web.WebCompanyStockQuote-2&q=universalName&universalName={}'.format(quote(company_username))
        resp = self.s.get(api_link, headers=headers).json()

resp = self.s.get('https://www.linkedin.com/voyager/api/search/blended?count=10&filters=List(currentCompany-%3E{},resultType-%3EPEOPLE)&origin=COMPANY_PAGE_CANNED_SEARCH&q=all&queryContext=List(spellCorrectionEnabled-%3Etrue)&start={}'.format(company_id,(int(page_no)-1) * 10), headers=headers).json()

**Comment by Jayasoruban** [comment]
pls tell me where to locate or find these two links from the code written

**Comment by mikebgrep** [comment]
Same error here @TufayelLUS do you will made some update of the code to work again.
