### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by syaifulabizar** [TufayelLUS/LinkedIn-Lead-Scraper#2]
i have problem with login. email and password already correct. but unable to login to linkedin,

**Comment by Boualami-Abdelmadjid** [comment]
Same problem for me

**Comment by Kaczmarczyk-M** [comment]
Any workaround for 6-digit code for identity verification?

**Comment by TufayelLUS** [comment]
If you're facing login-related issues, you may try the new 2024 version that I released a few days ago. It won't need you to log in through the automation script and it will use your existing browser cookies instead. It doesn't collect e-mails yet from the profiles but when I get time, I'll try adding that feature too.
