### ISSUE TITLE
error finding email

### ISSUE THREAD

**Issue by Daniel3356** [TufayelLUS/LinkedIn-Lead-Scraper#5]
Hi after installing all requirements with pip3 / python3.
I than enter my email and password if a valid linedin account inside: `linkedin_email =`  and `linkedin_password =` and I than put the link of the company's linkedin inside `target_company_link =`
and when I run` python3 Random_Scraper.py` or `python3 CompanyWise_Leads.py`
I get this: 
```
Logged in to LinkedIn!
Collecting all company member profiles upto 10000!

Traceback (most recent call last):
  File "................/linkedin-email/Random_Scraper.py", line 170, in <module>
    profile_list.extend(connection.listProfiles(company_id, page_no))
  File "................/linkedin-email/Random_Scraper.py", line 116, in listProfiles
    profiles = resp.get('elements')[0].get('elements')
IndexError: list index out of range
```

What should I do to fix it?
I'm on Python 3.10.2 and pip 22.2.

**Comment by AlorenaP** [comment]
Hello, have you managed to solve this problem? I am currently getting the same error, thank you if there is any solution.
