### ISSUE TITLE
No results : 

### ISSUE THREAD

**Issue by Trayserrr** [TufayelLUS/LinkedIn-Lead-Scraper#6]
```
Logged in to LinkedIn!
Collecting all company member profiles upto 10000!
Requesting page 1 for company ID 10953582
Response received: {'status': 404}
No data available in response
Profile list collected and saved! Extracting emails ...
Scanning 0 profiles

```

Would you know how to solve this ?

**Comment by TufayelLUS** [comment]
If you're trying the old version, potential chances exist that there may have been changes made to the LinkedIn API which is resulting in no data being returned against your given company link.
