### ISSUE TITLE
1K results or 10K results?

### ISSUE THREAD

**Issue by j92711** [TufayelLUS/LinkedIn-Lead-Scraper#7]
Hello,

Everytime I launch this script, I scrape 1000 results. In the About section, you mention that this script can "scrape up to 10k LinkedIn profiles from company profile links". How can we harvest 10K profiles? 

Notes:
* I select companies that have +10K employees (of course)
* I have changed the Do-For loop (that was set to 1000 iterations) to 10K iterations
* I am using a newly created Linkedin free account. Shall I use an old warmed up account? One with a Premium subscription?

**Comment by TufayelLUS** [comment]
Hi, thanks for sharing your concern. I have checked again and can see that LinkedIn has changed the limit to 1k records only. It used to collect 10k records 4 years ago when I first created this repository. Things have changed here and there, so we have to adjust to what we are offered now, unfortunately. This is a limitation from LinkedIn's end which we don't have control over.
