### ISSUE TITLE
CRF token issue

### ISSUE THREAD

**Issue by Assange333** [TufayelLUS/LinkedIn-Lead-Scraper#8]
Appreciate your project! was trying it out and experienced some issues

Had to adjust the CRF token slightly to match my Cookie 
'Csrf-Token': re.findall(r'JSESSIONID=ajax:(\d+)', cookies)[0],

but the following is the result

Error Message:
...

Failed to open https://www.linkedin.com/voyager/api/graphql?variables=(start:970,origin:COMPANY_PAGE_CANNED_SEARCH,query:(flagshipSearchIntent:SEARCH_SRP,queryParameters:List((key:currentCompany,value:List(2587)),(key:resultType,value:List(PEOPLE))),includeFiltersInResponse:false))&queryId=voyagerSearchDashClusters.e1f36c1a2618e5bb527c57bf0c7ebe9f
Checking facet: 980/990
Failed to open https://www.linkedin.com/voyager/api/graphql?variables=(start:980,origin:COMPANY_PAGE_CANNED_SEARCH,query:(flagshipSearchIntent:SEARCH_SRP,queryParameters:List((key:currentCompany,value:List(2587)),(key:resultType,value:List(PEOPLE))),includeFiltersInResponse:false))&queryId=voyagerSearchDashClusters.e1f36c1a2618e5bb527c57bf0c7ebe9f
Checking facet: 990/990
Failed to open https://www.linkedin.com/voyager/api/graphql?variables=(start:990,origin:COMPANY_PAGE_CANNED_SEARCH,query:(flagshipSearchIntent:SEARCH_SRP,queryParameters:List((key:currentCompany,value:List(2587)),(key:resultType,value:List(PEOPLE))),includeFiltersInResponse:false))&queryId=voyagerSearchDashClusters.e1f36c1a2618e5bb527c57bf0c7ebe9f

**Comment by TufayelLUS** [comment]
Hi, thank you for the appreciation. It might be a temporary issue with their API as I just tested and it seems to be working okay. So there could be some issues with their API on those last pages.
